"""Write one config file per sampled (mu, sigma) point.

Sweeping the synapse placement over a plane needs paired values, and Hydra's
sweeper takes the cross product of whatever it is given, so the pairs cannot be
expressed on the command line. Deriving them inside the job instead would leave
Hydra's snapshot of the run describing the defaults rather than what actually
ran, which is worse: the record would be wrong rather than merely absent.

So the pairs become a config group. Each file holds one point, Hydra composes it
like any other config, and `.hydra/config.yaml` in every job directory records
the values that were really used. Adding points later means adding files; the
ones already written keep their values, so a sample can be extended without
disturbing what has already been run.

    uv run make_samples.py --count 70
    uv run main.py -m 'sample=glob(*)' num_states=422 ...
"""

import argparse
import os

import numpy as np

CONF_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "conf", "sample")

TEMPLATE = """# @package _global_
# Generated by make_samples.py -- one sampled placement condition.
# seed is drawn per sample so that each point is an independent realisation:
# with a shared seed every run would draw the same variates and differ only in
# the weights applied to them, placing synapses at the same quantiles of
# whichever distribution (mu, sigma) describes.
sample_id: {sample_id}
seed: {seed}
syn_loc_mean: {mean:.4f}
syn_loc_std: {std:.4f}
"""


def write_samples(count, sampling_seed, mean_range, std_range, start):
    os.makedirs(CONF_DIR, exist_ok=True)
    written = []
    for sample_id in range(start, start + count):
        # Keyed on the id alone, so a given id always yields the same point no
        # matter how many are generated around it.
        rng = np.random.default_rng([sampling_seed, sample_id])
        mean = rng.uniform(*mean_range)
        std = rng.uniform(*std_range)
        seed = int(rng.integers(1, 2**31 - 1))

        path = os.path.join(CONF_DIR, f"s{sample_id:03d}.yaml")
        with open(path, "w") as f:
            f.write(TEMPLATE.format(sample_id=sample_id, seed=seed, mean=mean, std=std))
        written.append((sample_id, mean, std, seed))
    return written


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=70)
    parser.add_argument("--start", type=int, default=0,
                        help="first sample_id, for extending an existing sample")
    parser.add_argument("--sampling-seed", type=int, default=20260926)
    parser.add_argument("--mean-range", type=float, nargs=2, default=(0.0, 700.0))
    parser.add_argument("--std-range", type=float, nargs=2, default=(25.0, 500.0))
    args = parser.parse_args()

    written = write_samples(args.count, args.sampling_seed,
                            args.mean_range, args.std_range, args.start)
    print(f"Wrote {len(written)} files to {CONF_DIR}")
    for sample_id, mean, std, seed in written[:3]:
        print(f"  s{sample_id:03d}: syn_loc_mean={mean:.2f} syn_loc_std={std:.2f} seed={seed}")
    if len(written) > 3:
        print(f"  ... ({len(written) - 3} more)")


if __name__ == "__main__":
    main()
