# Default configurations for the reservoir simulation
defaults:
  - task: random
  - override hydra/launcher: joblib
  - _self_
hydra:
  job:
    chdir: True  # これをTrueにすると、プログラム実行中に自動でoutputs/...に移動します
  launcher: 
    n_jobs: 20  # ここを修正：launcherの下に配置する

# Shared parameters across different tasks and models
num_states: 100
reg: 1e-7
record_target: "calcium_acum" # Target variable for recording (e.g., potential, calcium_acum)
time_integration: True
seed: 1234                    # Random seed for reproducibility
exc_syn_tau1: 1               # Added: Required for synapse initialization
exc_syn_tau2: 5               # Added: Required for synapse initialization
syn_loc_condition: "gaussian" # uniform or gaussian or gaussian-apical or gaussian-basal
syn_loc_mean: 600
syn_loc_std:  100

cell_name: "cell1/"

gcalbar_ratio: null
gcanbar_ratio: null
gcatbar_ratio: null
gcakbar_ratio: null
gslowcakbar_ratio: null
